version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev


